### ISSUE TITLE
Django 1.7 simplejson Import error

### ISSUE THREAD

**Issue by benarito** [zapier/django-rest-hooks#13]
```
Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/lib/python2.7/site-packages/django/core/management/__init__.py", line 385, in execute_from_command_line
    utility.execute()
  File "lib/python2.7/site-packages/django/core/management/__init__.py", line 354, in execute
    django.setup()
  File "/lib/python2.7/site-packages/django/__init__.py", line 21, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/lib/python2.7/site-packages/django/apps/registry.py", line 108, in populate
    app_config.import_models(all_models)
  File "/lib/python2.7/site-packages/django/apps/config.py", line 197, in import_models
    self.models_module = import_module(models_module_name)
  File "/usr/local/Cellar/python/2.7.8_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/lib/python2.7/site-packages/rest_hooks/models.py", line 6, in <module>
    from django.utils import simplejson as json
ImportError: cannot import name simplejson
```

**Comment by avelis** [comment]
@benarito django-rest-hooks has made a new release (version 1.1.1) with a fix for this issue.

**Comment by benarito** [comment]
Great, Thanks.
