### ISSUE TITLE
Django 1.8+ support

### ISSUE THREAD

**Issue by briankung** [zapier/django-rest-hooks#20]
Another compatibility ticket! Tests fail in Django 1.8+ with the following error:

```
Traceback (most recent call last):
  File "runtests.py", line 44, in <module>
    django.setup()
  File "/Users/briankung/Envs/django-rest-hooks/lib/python3.4/site-packages/django/__init__.py", line 18, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/Users/briankung/Envs/django-rest-hooks/lib/python3.4/site-packages/django/apps/registry.py", line 85, in populate
    app_config = AppConfig.create(entry)
  File "/Users/briankung/Envs/django-rest-hooks/lib/python3.4/site-packages/django/apps/config.py", line 86, in create
    module = import_module(entry)
  File "/Users/briankung/Envs/django-rest-hooks/lib/python3.4/importlib/__init__.py", line 109, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 2254, in _gcd_import
  File "<frozen importlib._bootstrap>", line 2237, in _find_and_load
  File "<frozen importlib._bootstrap>", line 2224, in _find_and_load_unlocked
ImportError: No module named 'django_comments'
```

Specifically, tests fail in 1.8.0, 1.8.4, and 1.8.7, and pass with 1.7.7 and 1.7.11.

**Comment by briankung** [comment]
Sorry, didn't install the correct requirements file. Tests pass on 1.8 with `pip install -r devrequirements_1.8.txt`
